"use client";
import {useEffect,useState} from "react";
const groups=[
{id:"formforge",name:"FormForge",type:"Product / Fitness OS",desc:"Training, nutrition, recovery, configurable coaching influences, AI, and local-first data.",gh:"https://github.com/thacanadian/Formforge",live:"https://formforge-lake.vercel.app",shots:[["Dashboard","/projects/formforge-dashboard.webp"]]},
{id:"cinepulse",name:"CinePulse",type:"Product / Recommender",desc:"Adaptive taste profiles, cosine-similarity scoring, recency weighting, diversity reranking, moods, genres, ratings, and multi-profile signals.",gh:"https://github.com/thacanadian/cinepulse",cine:true},
{id:"leadsai",name:"LeadsAI",type:"Product / Sales Workspace",desc:"Discovery, qualification, pipeline movement, and personalized outreach in one focused workspace.",gh:"https://github.com/thacanadian/LeadsAI",shots:[["Lead Finder","/projects/leads-finder.webp"]]},
{id:"aerodetail-os",name:"AeroDetail OS",type:"Software / Operations",desc:"CRM, quoting, launch readiness, sales playbooks, jobs, QC, and secure operational workflows for Apex Aircraft Care.",gh:"https://github.com/thacanadian/AeroDetail-OS",shots:[["Dashboard","/projects/aero-dashboard.webp"]]},
{id:"neon-city",name:"Neon City",type:"Game / Prototype",desc:"Open-world systems experiment with driving, police heat, weapons, missions, progression, districts, and saves.",gh:"https://github.com/thacanadian/Neon-City"},
{id:"slice-to-fit",name:"Slice-to-Fit",type:"Game / Prototype",desc:"Touch-friendly slicing game with fit checks, power-ups, progression, limited attempts, and mobile controls.",gh:"https://github.com/thacanadian/Slice-to-Fit"},
{id:"gravity-shift",name:"Gravity Shift",type:"Game / Physics Puzzle",desc:"Directional-gravity chambers, star ratings, responsive controls, and local progression in a compact browser puzzle.",gh:"https://github.com/thacanadian/gravity-shift-game"},
{id:"apex-aircraft-care",name:"Apex Aircraft Care",type:"Venture / Founder Case Study",desc:"Positioning, pricing, prospecting, CRM, service design, safety research, SOPs, and operating systems.",gh:"https://github.com/thacanadian/Apex-Aircraft-Care"}
];
export default function Projects(){const[light,setLight]=useState(null);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return <main className="galleryPage"><nav className="galleryNav"><div className="shell"><a href="/">← Noah Krynicki</a><a href="mailto:noahwkry@gmail.com">Email me ↗</a></div></nav><header className="galleryHero shell"><span className="no">PROJECT ARCHIVE / 08 BUILDS</span><h1>Inside the<br/><em>work.</em></h1><p>Real interfaces, deeper context, and public-safe project proof. The homepage stays fast; this page gets to breathe.</p><div className="galleryIndex">{groups.map(g=><a key={g.id} href={`#${g.id}`}>{g.name}</a>)}</div></header><div className="shell">{groups.map(g=><section id={g.id} className="projectDetail" key={g.id}><div className="detailHead reveal"><div><span>{g.type}</span><h2>{g.name}</h2></div><div><p>{g.desc}</p><a className="goldLink" href={g.gh} target="_blank">GitHub ↗</a>{g.live&&<a className="goldLink" href={g.live} target="_blank">Live demo ↗</a>}</div></div>{g.shots?<div className="shotGrid">{g.shots.map(([cap,src])=><figure className="shot reveal" key={src}><button onClick={()=>setLight(src)}><img src={src} alt={`${g.name} ${cap}`}/></button><figcaption>{cap} · real interface</figcaption></figure>)}</div>:g.cine?<div className="cineDemo reveal"><span>TASTE DNA</span><h3>Find your next obsession.</h3><p>Adaptive ranking · mood discovery · diversity reranking · multiple profiles</p><div className="movieCards"><i/><i/><i/><i/></div></div>:<div className="placeholder reveal"><span>PUBLIC BUILD / DOCUMENTATION</span><h3>{g.name}</h3><p>Source and project documentation are linked above. A dedicated gameplay or field image can drop into this panel without changing the page structure.</p></div>}</section>)}</div>{light&&<div className="lightbox" onClick={()=>setLight(null)}><button aria-label="Close image">×</button><img src={light} alt="Expanded project screenshot"/></div>}</main>}