"use client";
import {useEffect,useState} from "react";
const groups=[
{id:"formforge",name:"FormForge",type:"Product / Fitness OS",desc:"Training, nutrition, recovery, configurable coaching influences, AI, security, local-first data, and a private beta of 20+ testers.",gh:"https://github.com/thacanadian/Formforge",shots:[["Dashboard","/projects/formforge-dashboard.webp"]]},
{id:"cinepulse",name:"CinePulse",type:"Product / Recommender",desc:"Adaptive taste profiles, cosine-similarity scoring, recency weighting, diversity reranking, moods, genres, ratings, and multi-profile signals.",gh:"https://github.com/thacanadian/cinepulse",cine:true},
{id:"leadsai",name:"LeadsAI",type:"Product / Sales Workspace",desc:"Discovery, qualification, pipeline movement, personalized outreach, APIs, automation, and web scraping in one focused workspace.",gh:"https://github.com/thacanadian/LeadsAI",shots:[["Lead Finder","/projects/leads-finder.webp"]]},
{id:"aerodetail-os",name:"AeroDetail OS",type:"Software / Operations",desc:"CRM, quoting, launch readiness, sales playbooks, jobs, QC, client records, and secure operational workflows for aviation service operations.",gh:"https://github.com/thacanadian/AeroDetail-OS",shots:[["Dashboard","/projects/aero-dashboard.webp"]]},
{id:"neon-city",name:"Neon City",type:"Game / Systems Prototype",desc:"Open-world systems experiment with driving, police heat, weapons, missions, progression, districts, AI behavior, and local saves.",gh:"https://github.com/thacanadian/Neon-City"},
{id:"slice-to-fit",name:"Slice-to-Fit",type:"Game / Mobile Prototype",desc:"Touch-friendly slicing game with fit checks, power-ups, progression, limited attempts, physics-style interactions, and mobile controls.",gh:"https://github.com/thacanadian/Slice-to-Fit"},
{id:"gravity-shift",name:"Gravity Shift",type:"Game / Physics Puzzle",desc:"Directional-gravity chambers, star ratings, responsive controls, physics interactions, and local progression in a compact browser puzzle.",gh:"https://github.com/thacanadian/gravity-shift-game"},
{id:"apex-aircraft-care",name:"Apex Aircraft Care",type:"Venture / Founder Case Study",desc:"Positioning, pricing, prospecting, CRM, automation, service design, safety research, SOPs, and operating systems for a DFW aviation-service venture.",gh:"https://github.com/thacanadian/Apex-Aircraft-Care"},
{id:"minecraft-systems",name:"Minecraft Systems",type:"Java / Mod Development",desc:"Java Edition Fabric and Spigot/Paper work including block-aware acoustic echo and echolocation mechanics, persistent world-history and reclaimed-ruins systems, and playable in-game guitar mechanics."},
{id:"startup-web",name:"Startup Web Development",type:"Independent / Client-style Work",desc:"Project-based support for 2–3 real early-stage startup ventures covering website code, interface design, analytics, SEO, API integrations, deployment support, and maintenance."},
{id:"tech-support",name:"Technical Production & IT Support",type:"Infrastructure / Live Systems",desc:"Hands-on troubleshooting across AV routing, servers, presentation systems, POS/payment hardware, printers, connectivity, routers, displays, accounts, software configuration, and end-user support."}
];
export default function Projects(){const[light,setLight]=useState(null);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return <main className="galleryPage"><nav className="galleryNav"><div className="shell"><a href="/">← Noah Krynicki</a><a href="/resume">Resume ↗</a></div></nav><header className="galleryHero shell"><span className="no">PROJECT ARCHIVE / 11 BUILDS & SYSTEMS</span><h1>Inside the<br/><em>work.</em></h1><p>Featured products first, then the smaller builds, experiments, client-style work, and technical systems that show breadth beyond the main résumé.</p><div className="galleryIndex">{groups.map(g=><a key={g.id} href={`#${g.id}`}>{g.name}</a>)}</div></header><div className="shell">{groups.map(g=><section id={g.id} className="projectDetail" key={g.id}><div className="detailHead reveal"><div><span>{g.type}</span><h2>{g.name}</h2></div><div><p>{g.desc}</p>{g.gh&&<a className="goldLink" href={g.gh} target="_blank" rel="noreferrer">GitHub ↗</a>}{g.live&&<a className="goldLink" href={g.live} target="_blank" rel="noreferrer">Live demo ↗</a>}</div></div>{g.shots?<div className="shotGrid">{g.shots.map(([cap,src])=><figure className="shot reveal" key={src}><button onClick={()=>setLight(src)} aria-label={`Expand ${g.name} ${cap} screenshot`}><img src={src} alt={`${g.name} ${cap}`}/></button><figcaption>{cap} · real interface</figcaption></figure>)}</div>:g.cine?<div className="cineDemo reveal"><span>TASTE DNA</span><h3>Find your next obsession.</h3><p>Adaptive ranking · mood discovery · diversity reranking · multiple profiles</p><div className="movieCards"><i/><i/><i/><i/></div></div>:<div className="placeholder reveal"><span>PROJECT / EXPERIENCE ARCHIVE</span><h3>{g.name}</h3><p>{g.gh?"Source and public-safe project documentation are linked above.":"Supporting details are summarized here without publishing private client, employer, or infrastructure information."}</p></div>}</section>)}</div>{light&&<div className="lightbox" onClick={()=>setLight(null)}><button aria-label="Close image">×</button><img src={light} alt="Expanded project screenshot"/></div>}</main>