"use client";
import {useEffect,useState} from "react";
const groups=[
{id:"formforge",name:"FormForge",type:"Product / Fitness OS",problem:"Fitness tools usually split training, nutrition, recovery, and coaching into separate products with separate data.",build:"Designed a local-first operating system that combines training, nutrition, recovery, configurable coaching influences, AI assistance, authentication, backups, and progress tracking.",proof:"Private beta with 20+ testers, real interface flows, automated testing, and public-safe source/documentation.",gh:"https://github.com/thacanadian/Formforge",shots:[["Dashboard","/projects/formforge-dashboard.webp"]]},
{id:"cinepulse",name:"CinePulse",type:"Product / Recommender",problem:"Most movie discovery tools over-index on generic popularity or a single rating instead of learning how a person’s taste changes by mood and context.",build:"Built adaptive taste profiles using ratings, reactions, watch history, genres, moods, recency, similarity scoring, and diversity reranking.",proof:"Functional recommendation prototype with persistent local profiles and a public GitHub project.",gh:"https://github.com/thacanadian/cinepulse",cine:true},
{id:"leadsai",name:"LeadsAI",type:"Product / Sales Workspace",problem:"Small teams bounce between lead databases, spreadsheets, research tabs, outreach tools, and pipeline boards just to start one conversation.",build:"Combined discovery, qualification, business research, pipeline movement, personalized outreach, APIs, automation, and web scraping in one focused desktop workspace.",proof:"Working desktop interface with lead finder, pipeline, and outreach flows plus public-safe documentation.",gh:"https://github.com/thacanadian/LeadsAI",shots:[["Lead Finder","/projects/leads-finder.webp"]]},
{id:"aerodetail-os",name:"AeroDetail OS",type:"Software / Operations",problem:"Launching a service business creates fragmented operational work: prospecting, quotes, jobs, QC, client records, safety checks, and launch readiness all drift into separate tools.",build:"Created a dedicated aviation-service operating system covering CRM, quoting, launch readiness, sales playbooks, jobs, QC, client records, and secure operational workflows.",proof:"Real internal interface used to structure Apex Aircraft Care’s launch and operating process.",gh:"https://github.com/thacanadian/AeroDetail-OS",shots:[["Dashboard","/projects/aero-dashboard.webp"]]},
{id:"neon-city",name:"Neon City",type:"Game / Systems Prototype",problem:"I wanted to test how many open-world systems could coexist in a browser without hiding behind a large engine or premade template.",build:"Built driving, police heat, weapons, missions, progression, districts, AI behavior, and local saves as a browser-based sandbox.",proof:"Playable prototype with public project source and systems documentation.",gh:"https://github.com/thacanadian/Neon-City"},
{id:"slice-to-fit",name:"Slice-to-Fit",type:"Game / Mobile Prototype",problem:"The design challenge was making a one-touch slicing mechanic understandable, replayable, and usable on mobile screens.",build:"Implemented fit checks, power-ups, progression, limited attempts, physics-style interactions, and touch controls.",proof:"Playable browser prototype with public source.",gh:"https://github.com/thacanadian/Slice-to-Fit"},
{id:"gravity-shift",name:"Gravity Shift",type:"Game / Physics Puzzle",problem:"The goal was to make gravity itself the core puzzle control instead of another movement mechanic.",build:"Created directional-gravity chambers, star ratings, responsive controls, physics interactions, and local progression.",proof:"Playable compact browser game with eight puzzle chambers and public source.",gh:"https://github.com/thacanadian/gravity-shift-game"},
{id:"apex-aircraft-care",name:"Apex Aircraft Care",type:"Venture / Founder Case Study",problem:"Start an aviation-service company without pretending to have experience, demand, or operating maturity before those things are earned.",build:"Built positioning, pricing, prospecting, CRM, automation, service design, safety research, SOPs, launch gates, and internal operating systems around an interior-first DFW strategy.",proof:"A real venture with outreach systems, prospect conversations, operating documents, and software built before scaling service claims.",gh:"https://github.com/thacanadian/Apex-Aircraft-Care"},
{id:"minecraft-systems",name:"Minecraft Systems",type:"Java / Mod Development",problem:"Use a familiar game as a sandbox for unusual simulation and persistence systems.",build:"Java Edition Fabric and Spigot/Paper work including block-aware acoustic echo and echolocation mechanics, persistent world-history and reclaimed-ruins systems, and playable in-game guitar mechanics.",proof:"Multiple custom Java systems built and tested in-game."},
{id:"startup-web",name:"Startup Web Development",type:"Independent / Client-style Work",problem:"Early-stage ventures often need a useful site and deployment help before they have a dedicated technical team.",build:"Project-based support covering website code, interface design, analytics, SEO, API integrations, deployment support, and maintenance.",proof:"Hands-on support across 2–3 real early-stage startup ventures without publishing private client material."},
{id:"tech-support",name:"Technical Production & IT Support",type:"Infrastructure / Live Systems",problem:"Live environments fail in messy, cross-system ways where the person troubleshooting rarely gets a clean error message.",build:"Worked across AV routing, servers, presentation systems, POS/payment hardware, printers, connectivity, routers, displays, accounts, software configuration, and end-user support.",proof:"Repeated real-world troubleshooting in workplace and volunteer live-production environments."}
];
export default function Projects(){const[light,setLight]=useState(null);useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>io.observe(e));return()=>io.disconnect()},[]);return <main className="galleryPage"><nav className="galleryNav"><div className="shell"><a href="/">← Noah Krynicki</a><a href="/resume">Resume ↗</a></div></nav><header className="galleryHero shell"><div className="breadcrumb"><a href="/">Home</a> / Projects</div><span className="no">PROJECT ARCHIVE / 11 BUILDS & SYSTEMS</span><h1>Inside the<br/><em>work.</em></h1><p>Not just thumbnails. Each section explains the problem, what I built, and the proof that exists today.</p><div className="galleryIndex">{groups.map(g=><a key={g.id} href={`#${g.id}`}>{g.name}</a>)}</div></header><div className="shell">{groups.map(g=><section id={g.id} className="projectDetail" key={g.id}><div className="detailHead reveal"><div><span>{g.type}</span><h2>{g.name}</h2></div><div className="caseCopy"><div className="caseLine"><b>Problem</b><p>{g.problem}</p></div><div className="caseLine"><b>Build</b><p>{g.build}</p></div><div className="caseLine"><b>Proof</b><p>{g.proof}</p></div>{g.gh&&<a className="goldLink" href={g.gh} target="_blank" rel="noreferrer">GitHub ↗</a>}{g.live&&<a className="goldLink" href={g.live} target="_blank" rel="noreferrer">Live demo ↗</a>}</div></div>{g.shots?<div className="shotGrid">{g.shots.map(([cap,src])=><figure className="shot reveal" key={src}><button onClick={()=>setLight(src)} aria-label={`Expand ${g.name} ${cap} screenshot`}><img src={src} alt={`${g.name} ${cap} real product interface screenshot`}/></button><figcaption>{cap} · real interface</figcaption></figure>)}</div>:g.cine?<div className="cineDemo reveal"><span>TASTE DNA</span><h3>Find your next obsession.</h3><p>Adaptive ranking · mood discovery · diversity reranking · multiple profiles</p><div className="movieCards"><i/><i/><i/><i/></div></div>:<div className="placeholder reveal"><span>PROJECT / EXPERIENCE ARCHIVE</span><h3>{g.name}</h3><p>{g.gh?"Public source or project documentation is linked above. A real cover image or gameplay capture can replace this panel without changing the case study.":"Supporting details are summarized here without publishing private client, employer, or infrastructure information."}</p></div>}</section>)}</div>{light&&<div className="lightbox" onClick={()=>setLight(null)}><button aria-label="Close image">×</button><img src={light} alt="Expanded real project screenshot"/></div>}</main>}
