"use client";
import {useEffect,useState} from "react";

const projects=[
{id:"formforge",n:"01",name:"FormForge",type:"Product",status:"20+ beta testers",desc:"A privacy-focused fitness operating system spanning training, nutrition, recovery, progress, backups, and AI-assisted coaching, now being validated with a private beta group of 20+ testers.",tags:["Go","PWA","Local-first","Security"],href:"https://github.com/thacanadian/Formforge",cover:"/projects/formforge-cover.webp"},
{id:"cinepulse",n:"02",name:"CinePulse",type:"Product",status:"New build",desc:"An adaptive movie discovery system that learns from ratings, reactions, watch history, genres, moods, recency, and exploration preferences.",tags:["JavaScript","Recommendation Engine","Local-first","Responsive UI"],href:"https://github.com/thacanadian/cinepulse",cover:"/projects/cinepulse-cover.webp"},
{id:"leadsai",n:"03",name:"LeadsAI",type:"Product",status:"Case study",desc:"A cross-platform lead discovery, outreach, and sales-pipeline system designed to move a prospect from research to conversation.",tags:["TypeScript","React Native","Electron","APIs"],href:"https://github.com/thacanadian/LeadsAI",cover:"/projects/leadsai-cover.webp"},
{id:"aeroops",n:"04",name:"AeroOps",type:"Software",status:"In development",desc:"A production-style aviation operations platform focused on authenticated workflows, fleet visibility, scheduling, maintenance, reporting, APIs, and operational data.",tags:["Backend","APIs","Auth","Aviation"],privateRepo:true,cover:"/projects/aeroops-cover.webp"},
{id:"lessonloop",n:"05",name:"LessonLoop",type:"Product",status:"Prototype",desc:"A mobile-first lesson recap system that helps teachers keep students and parents aligned through clear recaps, progress signals, and lightweight follow-up.",tags:["Product Design","Education","Mobile-first","Workflow"],cover:"/projects/lessonloop-cover.webp"},
{id:"aerodetail-os",n:"06",name:"AeroDetail OS",type:"Software",status:"v2.1.4",desc:"A secure aircraft-detailing operating system spanning CRM, quoting, jobs, launch planning, client records, and sales workflows.",tags:["Python","JavaScript","Security","Operations"],href:"https://github.com/thacanadian/AeroDetail-OS",visual:"/projects/aero-dashboard.webp"},
{id:"neon-city",n:"07",name:"Neon City",type:"Game",status:"Playable",desc:"A browser-based open-world experiment with driving, missions, police AI, weapons, progression, and a living city sandbox.",tags:["JavaScript","Three.js","Game Systems","AI Behavior"],href:"https://github.com/thacanadian/Neon-City",kind:"city"},
{id:"slice-to-fit",n:"08",name:"Slice-to-Fit",type:"Game",status:"Prototype",desc:"A browser game about slicing objects into the right shape, managing limited attempts, and launching pieces through moving cutouts.",tags:["JavaScript","Canvas","Touch","Game Design"],href:"https://github.com/thacanadian/Slice-to-Fit",kind:"slice"},
{id:"gravity-shift",n:"09",name:"Gravity Shift",type:"Game",status:"Playable",desc:"A compact physics puzzle with directional gravity, chambers, star ratings, responsive controls, and local progression.",tags:["JavaScript","Canvas","Physics","Mobile"],href:"https://github.com/thacanadian/gravity-shift-game",kind:"gravity"},
{id:"apex-aircraft-care",n:"10",name:"Apex Aircraft Care",type:"Venture",status:"Early stage",desc:"A DFW aircraft appearance company built from positioning and unit economics through operations, outreach, CRM systems, and service standards.",tags:["Founder","Operations","Sales Systems","Brand"],href:"https://github.com/thacanadian/Apex-Aircraft-Care",cover:"/projects/apex-cover.webp"}
];

function Visual({p}){
 if(p.cover)return <div className="visual coverVisual"><div className="coverMedia"><img src={p.cover} alt={`${p.name} project cover showing the product and interface`}/></div><span className="coverShade"/><span className="coverLabel">OPEN CASE STUDY ↗</span><span className="visualScan"/></div>;
 if(p.visual)return <div className="visual real"><img src={p.visual} alt={`${p.name} product interface screenshot`}/><span className="visualScan"/></div>;
 if(p.kind==="city")return <div className="visual city"><div className="moon"/><i/><i/><i/><b>NEON CITY</b></div>;
 if(p.kind==="slice")return <div className="visual slice"><i/><i/><b>SLICE · SELECT · LAUNCH</b></div>;
 if(p.kind==="gravity")return <div className="visual slice gravityVisual"><i/><i/><b>SHIFT GRAVITY · CLEAR THE CHAMBER</b></div>;
 return null;
}

const faqs=[
["What kinds of roles are you targeting?","Product, technical operations, implementation, customer success, business systems, and early-stage teams where I can own real problems instead of staying boxed into one narrow function."],
["Are these real projects?","Yes. The project archive links public-safe source, documentation, and real interface screenshots where available. I separate prototypes, active products, private-source work, and founder work instead of presenting everything as production software."],
["What do you actually build with?","My work spans JavaScript, React, Next.js, Go, Python, APIs, automation, local-first systems, browser games, CRM workflows, and the business processes around the software."],
["Where are you based?","Fort Worth / DFW, Texas. I’m open to strong local opportunities and remote or hybrid roles depending on the team."],
["How quickly do you respond?","Email is the best route. I aim to reply to serious opportunities within one business day."]
];

export default function Home(){
 const[filter,setFilter]=useState("All");
 useEffect(()=>{
  const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});
  document.querySelectorAll(".reveal").forEach(e=>io.observe(e));
  const move=e=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",e.clientY+"px");const h=document.querySelector(".hero h1");if(h&&matchMedia("(pointer:fine)").matches)h.style.transform=`translate3d(${(e.clientX/innerWidth-.5)*10}px,${(e.clientY/innerHeight-.5)*6}px,0)`;const c=e.target.closest?.(".project");if(c&&matchMedia("(pointer:fine)").matches){const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;c.style.setProperty("--cx",x*100+"%");c.style.setProperty("--cy",y*100+"%");c.style.setProperty("--cover-x",`${(x-.5)*-14}px`);c.style.setProperty("--cover-y",`${(y-.5)*-10}px`);c.style.transform=`perspective(1100px) rotateX(${(.5-y)*4.5}deg) rotateY(${(x-.5)*4.5}deg) translateY(-6px) scale(1.006)`}};
  const out=e=>{const c=e.target.closest?.(".project");if(c&&!c.contains(e.relatedTarget)){c.style.transform="";c.style.removeProperty("--cover-x");c.style.removeProperty("--cover-y")}};
  const scroll=()=>{const d=document.documentElement,p=document.querySelector("#progress");if(p)p.style.width=(d.scrollTop/(d.scrollHeight-d.clientHeight||1)*100)+"%"};
  addEventListener("mousemove",move,{passive:true});addEventListener("mouseout",out);addEventListener("scroll",scroll,{passive:true});
  return()=>{io.disconnect();removeEventListener("mousemove",move);removeEventListener("mouseout",out);removeEventListener("scroll",scroll)}
 },[filter]);
 const list=filter==="All"?projects:projects.filter(p=>p.type===filter);
 return <main><div id="progress"/><nav className="nav shell"><a className="brand magnetic" href="#top" aria-label="Noah Krynicki home">NK</a><div className="navlinks"><a href="#work">Work</a><a href="/projects">Projects</a><a href="#about">About</a><a href="#experience">Experience</a><a href="#faq">FAQ</a><a href="#contact">Contact</a></div><div className="navright"><a className="resume" href="/resume">Resume ↓</a><a href="mailto:noahwkry@gmail.com">Email me ↗</a></div></nav>
 <header id="top" className="hero shell"><div className="availability"><i/> OPEN TO PRODUCT, TECHNICAL OPERATIONS & IMPLEMENTATION ROLES</div><h1>I build systems<br/><span>that move work forward.</span></h1><div className="heroBottom"><div><p>I’m <strong>Noah Krynicki</strong>, a DFW-based operator and product builder who leads teams, ships software, validates products with real users, and turns rough ideas into executable business systems.</p><div className="heroCtas"><a className="button magnetic" href="/projects">See the work ↗</a><a className="button alt magnetic" href="mailto:noahwkry@gmail.com">Talk to me ↗</a></div></div><a className="circle magnetic" href="#work" aria-label="Scroll to selected work">→</a></div><div className="heroIndex"><span>FORT WORTH / DFW, TX</span><span>PRODUCT · TECHNICAL OPERATIONS · BUSINESS SYSTEMS</span></div></header>
 <div className="proof"><div className="shell proofGrid reveal"><div><b>20+</b><span>FormForge beta testers</span></div><div><b>50+</b><span>Students led</span></div><div><b>20+</b><span>Teammates trained</span></div><div><b>0→1</b><span>Founder experience</span></div></div></div>
 <section id="work" className="work"><div className="shell"><div className="head reveal"><div><span className="no">01</span><h2>Selected work</h2></div><p>Real products, experiments, and ventures. Open a project to see the deeper proof, screenshots, and source.</p></div><div className="filters reveal">{["All","Product","Software","Game","Venture"].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?"active":""} aria-pressed={filter===x}>{x}</button>)}</div><div className="grid">{list.map((p,i)=><article className="project reveal" style={{animationDelay:`${i*55}ms`}} key={p.name}><div className="projectGlow"/><a className="visualLink" href={`/projects#${p.id}`} aria-label={`Open ${p.name} case study`}><Visual p={p}/></a><div className="meta"><span>{p.n} / {p.type}</span><em>{p.status}</em></div><h3>{p.name}</h3><p>{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="actions"><a href={`/projects#${p.id}`}>Case study ↗</a>{p.href&&<a href={p.href} target="_blank" rel="noreferrer">GitHub ↗</a>}{p.privateRepo&&<span className="privateRepo">Private repo</span>}</div></article>)}</div><a className="galleryCta reveal magnetic" href="/projects">Explore the full project gallery ↗</a></div></section>
 <section id="about"><div className="shell"><div className="head light reveal"><div><span className="no">02</span><h2>About</h2></div></div><div className="aboutGrid"><div className="portrait reveal"><img src="https://avatars.githubusercontent.com/u/146765811?v=4" alt="Portrait of Noah Krynicki"/></div><div className="copy reveal"><p className="lead">I lead people, build products, and make messy workflows executable.</p><p>I’m completing a Bachelor of Business Administration at Western Governors University, expected May 2028, while building software and business systems in the real world. I’m also completing Texas Real Estate Sales Agent licensing requirements.</p><div className="principles"><div><b>01</b>Build before bragging</div><div><b>02</b>Measure what ships</div><div><b>03</b>Stay curious and useful</div></div><p className="locationLine">Based in <a href="https://www.google.com/maps/search/?api=1&query=Fort+Worth+Texas" target="_blank" rel="noreferrer">Fort Worth / DFW, Texas ↗</a></p></div></div></div></section>
 <section id="experience" className="experience"><div className="shell"><div className="head light reveal"><div><span className="no">03</span><h2>Experience</h2></div><p>A practical mix of building, leading, selling, and serving.</p></div><div className="timeline reveal"><div className="row"><span>2026 — NOW</span><h3>Apex Aircraft Care</h3><p>Founder</p><em>Brand, research, systems, service strategy, CRM, sales infrastructure, and go-to-market foundation.</em></div><div className="row"><span>2025 — NOW</span><h3>Independent Products</h3><p>Product Builder</p><em>Built and shipped software including FormForge, CinePulse, LeadsAI, AeroOps, LessonLoop, and additional workflow and browser projects.</em></div><div className="row"><span>2025 — NOW</span><h3>Andy’s Frozen Custard</h3><p>Manager</p><em>Lead shifts of 4–7, train teammates, and resolve customer and operating issues in a high-volume environment serving hundreds of guests each day.</em></div><div className="row"><span>2025 — 2026</span><h3>Raising Cane’s</h3><p>Trainer</p><em>Promoted to Trainer and onboarded 20+ teammates.</em></div><div className="row"><span>2026 — 2028</span><h3>Western Governors University</h3><p>Bachelor of Business Administration</p><em>Degree in progress · Expected May 2028.</em></div><div className="row"><span>IN PROGRESS</span><h3>Texas Real Estate Licensing</h3><p>Sales Agent Requirements</p><em>Completing Texas licensing requirements; not yet represented as an issued license.</em></div></div></div></section>
 <section id="faq" className="faqSection"><div className="shell"><div className="head reveal"><div><span className="no">04</span><h2>Quick answers</h2></div><p>The questions a recruiter or collaborator usually wants answered before reaching out.</p></div><div className="faqGrid">{faqs.map(([q,a],i)=><details className="faqItem reveal" key={q}><summary><span>{String(i+1).padStart(2,"0")}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></section>
 <section id="contact" className="contact shell"><span className="no reveal">05 / CONTACT</span><h2 className="reveal">Have something worth<br/><em>building?</em></h2><p className="reveal">I’m looking for product, technical operations, implementation, customer success, and business-systems roles where initiative and systems thinking matter.</p><p className="responsePromise reveal">Best route: email. I aim to reply to serious opportunities within one business day.</p><div className="buttons reveal"><a className="button magnetic" href="mailto:noahwkry@gmail.com">Email me ↗</a><a className="button alt magnetic" href="/resume">Resume ↓</a><a className="button alt magnetic" href="https://www.linkedin.com/in/noah-krynicki-48513b312/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></section>
 <footer className="footer shell"><strong>NK</strong><span>© 2026 Noah Krynicki</span><span><a href="/privacy">Privacy</a> · <a href="https://github.com/thacanadian">GitHub</a> · <a href="#top">Back to top ↑</a></span></footer><div className="mobileCta"><a href="/projects">Projects</a><a href="mailto:noahwkry@gmail.com">Email me ↗</a></div></main>
}
